### ISSUE TITLE
Silicon smelter texture was created by me

### ISSUE THREAD

**Issue by max8rr8** [KeviTV/MekanisM#2]
Add file named CONTRIBUTORS

**Comment by Fatonndev** [comment]
-
   - Download a newer version of the mod. I have my own texture.
   -
   2
   <https://translate.google.by/>

<https://translate.google.by/>

пн, 4 нояб. 2019 г. в 07:49, Max <notifications@github.com>:

**Comment by max8rr8** [comment]
Yes, i have already notice it, that is why i close issue
